---
extends: default

ignore:
  - .git/
  # bundle/ contains generated contents
  - bundle/
  # vendor/ are maintained elsewhere
  - vendor/
  # Template files contain Go templating syntax that yamllint cannot parse
  - test/e2e/helpers/templates/

rules:
  document-start:
    ignore:
      - config/manager/
      - deploy/
  indentation:
    ignore:
      - config/
      - deploy/
  line-length:
    ignore:
      - config/
      - deploy/
